services:
  db:
    container_name: postgres_container
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"


  redis:
    container_name: redis_container
    image: redis:latest
    ports:
      - "6379:6379"


  web:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

volumes:
  postgres_data: